# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  drupal:
    build: .

    ports:
      - "8080:80"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data: